/*
 *  PROJECT ToooT (ToooT_UI)
 *  Copyright (c) 2026 Apple Core Audio / Pro Apps Division.
 *  60FPS Real-Time Hardware Visualizer.
 */

import MetalKit
import ToooT_Core

/// 60FPS Render loop strictly decoupled from the main thread.
/// Takes live pointers generated by `DSPContext.swift` inside the real-time block
/// and draws them using `MTLCommandQueue` execution boundaries.
public final class MetalRenderer: NSObject, MTKViewDelegate, @unchecked Sendable {
    
    private let device: MTLDevice
    private let commandQueue: MTLCommandQueue
    private var pipelineState: MTLRenderPipelineState?
    private let state: PlaybackState
    
    // Cached copy of peakLevel pushed from @MainActor — safe to read on draw thread.
    // arm64 word-sized stores are atomic; worst case is one stale frame.
    nonisolated(unsafe) var cachedPeakLevel: Float = 0.0
    
    // MVP Dummy Buffer simulating real-time audio layout
    private var dummyAudioBuffer: MTLBuffer?
    
    public init(state: PlaybackState) {
        let device = MTLCreateSystemDefaultDevice()!
        self.device = device
        self.commandQueue = device.makeCommandQueue()!
        self.state = state
        super.init()
        
        // Construct a unified memory buffer matching 1024 frames of float data.
        let size = 1024 * MemoryLayout<Float>.stride
        self.dummyAudioBuffer = device.makeBuffer(length: size, options: .storageModeShared)
        
        Task {
            do {
                // Fixed pixel format for pre-warming consistency
                self.pipelineState = try await MetalResourceManager.shared.prepareSpectrogramPipeline(pixelFormat: .bgra8Unorm)
            } catch {
                print("MetalRenderer failed to prepare: \(error)")
            }
        }
    }
    
    public func mtkView(_ view: MTKView, drawableSizeWillChange size: CGSize) {}
    
    private var timeOffset: Double = 0.0
    
    public func draw(in view: MTKView) {
        guard let drawable = view.currentDrawable,
              let descriptor = view.currentRenderPassDescriptor,
              let pipeline = pipelineState,
              let buffer = dummyAudioBuffer else { return }
        
        // Dynamically animate the wave
        timeOffset += 0.03
        let time = Float(timeOffset)
        let pt = buffer.contents().bindMemory(to: Float.self, capacity: 1024)
        
        // Use peak level from the playback state to drive the amplitude
        let amplitude = max(0.05, cachedPeakLevel * 2.0)
        
        for i in 0..<1024 {
            let x = Float(i) / 1024.0
            let phase1 = x * .pi * 12 + time * 1.2
            let phase2 = x * .pi * 20 - time * 0.8
            let phase3 = x * .pi * 4 + time * 2.0
            let envelope = sin(x * .pi) // Taper edges to 0
            
            // Mix three waves for a cool visual
            pt[i] = (sin(phase1) * 0.4 + sin(phase2) * 0.2 + cos(phase3) * 0.3) * envelope * amplitude
        }
        
        let commandBuffer = commandQueue.makeCommandBuffer()
        let encoder = commandBuffer?.makeRenderCommandEncoder(descriptor: descriptor)
        
        encoder?.setRenderPipelineState(pipeline)
        
        // Bind the audio unified memory buffer directly to Shader input register 0
        encoder?.setVertexBuffer(buffer, offset: 0, index: 0)
        
        // Draw 1024 points as a linear Line Strip forming the spectrogram trace
        encoder?.drawPrimitives(type: .lineStrip, vertexStart: 0, vertexCount: 1024)
        encoder?.endEncoding()
        
        commandBuffer?.present(drawable)
        commandBuffer?.commit()
    }
}
